import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const out = process.env.OUT || '.';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 390, height: 760 } })).newPage();
await p.goto('http://localhost:8123/?q=1&dev=1&tod=afternoon'); await p.waitForSelector('#modal.on #mok', { timeout: 120000 }); await p.click('#mok'); await p.waitForTimeout(3000);
const clip = { x: 100, y: 480, width: 200, height: 160 };
await p.screenshot({ path: out + '/o0.png', clip });
const hide = async (n, fn) => { await p.evaluate(fn); await p.waitForTimeout(3500); await p.screenshot({ path: out + `/o${n}.png`, clip }); };
await hide(1, () => { const T = window.__tank; T.scene.children.forEach((c) => { if (c.isMesh && c.geometry.type === 'PlaneGeometry' && c.material.blending === 2) c.visible = false; }); });
await hide(2, () => { const T = window.__tank; T.scene.children.forEach((c) => { if (c.isPoints || c.isSprite) c.visible = false; }); });
await hide(3, () => { const T = window.__tank; T.scene.children.forEach((c) => { if (c.isGroup) c.visible = false; }); });
console.log('FINISHED'); await b.close();
