// Big look at every species at side and three-quarter view. OUT=file node tools/gallery2.mjs [ids...]
import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const base = process.env.BASE || 'http://localhost:8123', out = process.env.OUT || '/tmp/gallery2.png', only = process.argv.slice(2);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 1000, height: 800 } })).newPage(); const errors = []; p.on('pageerror', (e) => errors.push(e.message));
await p.goto(base + '/?q=1&dev=1'); await p.waitForSelector('#modal.on #mok', { timeout: 120000 });
const imgs = await p.evaluate(async (only) => { const v = await import('/src/voxel.js'), sp = await import('/src/species.js'); const o = []; for (const k of Object.keys(sp.SPECIES)) { if (only.length && !only.includes(k)) continue; const f = new v.Fish(sp.SPECIES[k], 3); const make = (yaw) => { const c = f.frame({ yaw }); const d = document.createElement('canvas'); d.width = d.height = 300; const g = d.getContext('2d'); g.imageSmoothingEnabled = false; const k2 = Math.max(1, Math.floor(290 / Math.max(c.width, c.height))); g.drawImage(c, (300 - c.width * k2) / 2, (300 - c.height * k2) / 2, c.width * k2, c.height * k2); return d.toDataURL(); }; o.push([k, sp.SPECIES[k].label, make(0), make(0.7)]); } return o; }, only);
await p.setContent(`<body style="margin:0;background:#2a7aa8;display:grid;grid-template-columns:repeat(3,320px);gap:4px;padding:6px;font:12px sans-serif;color:#fff">${imgs.map(([k, l, a, b2]) => `<div style="text-align:center"><div style="display:flex"><img src="${a}" width=150 height=150><img src="${b2}" width=150 height=150></div>${l}</div>`).join('')}</body>`);
await p.setViewportSize({ width: 1000, height: Math.ceil(imgs.length / 3) * 190 + 20 }); await p.screenshot({ path: out }); console.log(errors.length ? 'errors: ' + errors.join('; ') : 'ok', imgs.length); await b.close();
