// An octopus that lives in a coconut picks the whole shell up, carries it somewhere new, sets it down and tucks in under it there.
// Steps the simulation by hand. Needs the solo game on 8123. node tools/octopus_relocate.mjs OUTDIR
import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const out = process.argv[2] || '/tmp/relocate'; fs.mkdirSync(out, { recursive: true });
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 390, height: 760 } })).newPage(); const errors = []; let fails = 0; p.on('pageerror', (e) => errors.push(e.message));
const ck = (n, ok, x = '') => { console.log(ok ? '  ✓' : '  ✗', n, x); if (!ok) fails++; };
await p.goto('http://localhost:8123/?q=0&dev=1&tod=afternoon'); await p.waitForSelector('#modal.on #mok', { timeout: 120000 }); await p.click('#mok');
await p.waitForFunction(() => window.__game?.state, null, { timeout: 120000 }); await p.waitForTimeout(2500);
await p.evaluate(() => { const g = window.__game, s = g.state; s.flags.tut = 5; s.fish.length = 0; s.fish.push({ id: 'x1', name: 'Inky', species: 'octopus', seed: 5, born: Date.now() - 12 * 864e5, stage: 'adult', traits: ['Calm'], happy: 0.8, health: 1, owner: 'me', ownerName: 'You', home: 'c1', movedAt: 0 });
  s.decor.length = 0; s.decor.push({ id: 'c1', type: 'coconut', x: 2.4, z: 1.5, ry: 0 }); g.emit('state'); document.querySelectorAll('#goal,#coach,#toast,#modal,#settle,#reunion,#fishpill').forEach((e) => (e.style.display = 'none')); });
await p.waitForTimeout(2500);
const r0 = await p.evaluate(() => { const F = window.__fishes, f = F.list[0]; f.pos.set(0.5, 0.6, 1.0); f.vel.set(0, 0, 0); f.inspect = null; f.st = { s: 'rest', t: 999, n: 0, pulse: 0 };
  let plan = null; for (let i = 0; i < 30 && !(plan && plan.kind === 'home'); i++) plan = F.planMove(f, f.mind ?? { tidy: 0.5 }, { relocate: true }); if (plan?.kind !== 'home') return { plan };
  F.beginTask(f, plan); if (window.__dbg === undefined) { window.__dbg = []; const orig = F.taskEvent.bind(F); F.taskEvent = (ff, ev) => { const r = orig(ff, ev); window.__dbg.push(['ev', ev, r, ff.task?.stage ?? null, +ff.pos.x.toFixed(2), +ff.pos.z.toFixed(2), 's', ff.st?.s, 'scare', ff.scareT, 'seek', !!ff.seeking, 'glass', !!ff.glassAt, 'hunt', !!ff.hunt, 'jar', !!ff.jarAt, 'n', ff.st?.prog?.n, 'age', ff.task ? Math.round(performance.now() - ff.task.t0) : null]); return r; }; let cur = f.task; Object.defineProperty(f, 'task', { get: () => cur, set: (v) => { if (!v && cur) window.__dbg.push(['task=null', new Error().stack.split('\n').slice(1, 9).map((l) => l.trim().replace(/http:\/\/localhost:8123\/src\/w3\//, '')).join(' | ')]); cur = v; } }); } return { plan, task: f.task?.kind }; });
console.log('  plan', JSON.stringify(r0.plan)); ck('it plans to carry its shell somewhere new', r0.plan?.kind === 'home' && r0.task === 'home');
let carried = false, trail = [];
for (let i = 0; i < 320; i++) { const st = await p.evaluate(() => { const F = window.__fishes, f = F.list[0]; for (let k = 0; k < 10; k++) { F.update(0.05, (window.__t = (window.__t ?? 0) + 0.05)); F.list.forEach((x) => x.update(0.05, Math.random, F.list)); } const it = [...window.__decor.items.values()][0], d = window.__game.state.decor[0], [gx, gz] = f.denGoal(Math.random); window.__cam = [it.group.position.x + 0.8, 2.0, it.group.position.z + 8.5, it.group.position.x, 0.4, it.group.position.z]; const V = f.pos.constructor, o = new V(), W = f.constructor.world, nb = W.push(new V(f.pos.x, f.pos.y, f.pos.z), f.cr, o); return { sp: [+(f.speed ?? 1).toFixed(2), +(f.mul ?? 1).toFixed(2), +(f.vigor ?? 1).toFixed(2), +(f.tmul ?? 1).toFixed(2), f.profile?.mood, f.weak, f.tired], vx: +f.vel.x.toFixed(3), vz: +f.vel.z.toFixed(3), y: +f.pos.y.toFixed(2), push: [nb, +o.x.toFixed(2), +o.z.toFixed(2)], homing: f.homing, why: [f.scareT > 0 ? 'scare' : '', f.seeking ? 'seek' : '', f.glassAt ? 'glass' : '', f.hunt ? 'hunt' : '', f.jarAt ? 'jar' : '', f.task && performance.now() - f.task.t0 > 240000 ? 'old' : ''].filter(Boolean).join(','), fx: +f.pos.x.toFixed(2), fz: +f.pos.z.toFixed(2), tgt: [+f.target.x.toFixed(2), +f.target.z.toFixed(2)], n: f.st?.prog?.n, ax: f.task ? +f.task.ax.toFixed(2) : null, az: f.task ? +f.task.az.toFixed(2) : null, stage: f.task?.stage ?? null, mode: f.st?.mode, s: f.st?.s, lift: +it.group.position.y.toFixed(2), at: [+d.x.toFixed(2), +d.z.toFixed(2)], den: f.den ? [+f.den.x.toFixed(2), +f.den.z.toFixed(2)] : null, dist: +Math.hypot(f.pos.x - gx, f.pos.z - gz).toFixed(2), tuck: +(f.tuckK ?? 0).toFixed(2) }; }); trail.push(st); if (st.stage === 'haul' && st.lift > 0.2 && !carried) { carried = true; await p.waitForTimeout(1500); await p.screenshot({ path: out + '/relocate_carry.png' }); } if (st.s === 'rest' && !st.mode && st.stage == null && i > 40 && st.dist < 0.5) break; }
if (process.env.DEBUG) { for (const st of trail.slice(0, 6)) console.log('   ', JSON.stringify(st)); console.log('   events', JSON.stringify(await p.evaluate(() => window.__dbg))); }
await p.evaluate(() => { const F = window.__fishes; for (let k = 0; k < 80; k++) { F.update(0.05, (window.__t = (window.__t ?? 0) + 0.05)); F.list.forEach((x) => x.update(0.05, Math.random, F.list)); } });      // a few seconds more, to settle in
trail.push(await p.evaluate(() => { const F = window.__fishes, f = F.list[0], d = window.__game.state.decor[0], [gx, gz] = f.denGoal(Math.random); return { s: f.st?.s, mode: f.st?.mode, stage: f.task?.stage ?? null, at: [+d.x.toFixed(2), +d.z.toFixed(2)], den: f.den ? [+f.den.x.toFixed(2), +f.den.z.toFixed(2)] : null, dist: +Math.hypot(f.pos.x - gx, f.pos.z - gz).toFixed(2), tuck: +(f.tuckK ?? 0).toFixed(2) }; }));
const last = trail.at(-1); await p.waitForTimeout(1500); await p.screenshot({ path: out + '/relocate_done.png' }); console.log('  end', JSON.stringify(last));
ck('it carried the shell (lifted, in its arms)', carried);
ck('the shell is at the new place in the game state', Math.hypot(last.at[0] - r0.plan.gx, last.at[1] - r0.plan.gz) < 0.3, JSON.stringify(last.at));
ck('and its den moved with it', last.den && Math.hypot(last.den[0] - last.at[0], last.den[1] - last.at[1]) < 0.3);
ck('it settled in under the shell at the new place', last.s === 'rest' && last.dist < 0.5 && last.tuck > 0.15, `dist ${last.dist} tuck ${last.tuck}`);
ck('no page errors', errors.length === 0, errors.join('; '));
console.log(fails ? `${fails} failed` : 'Relocate checks passed'); await b.close(); process.exit(fails ? 1 : 0);
