// Plays the whole solo game through the real interface: tutorial, feeding, shopping, placing, adopting, levelling.
import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const base = process.env.BASE || 'http://localhost:8123', out = process.env.OUT || '.';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 390, height: 760 } })).newPage();
const errors = []; p.on('pageerror', (e) => errors.push(e.message)); p.on('console', (m) => { if (m.type() === 'error' && !/404|Failed to load/.test(m.text())) errors.push(m.text().slice(0, 200)); });
let fails = 0; const ck = (name, ok, extra = '') => { console.log(ok ? '  ✓' : '  ✗', name, extra); if (!ok) fails++; };
const S = () => p.evaluate(() => JSON.parse(JSON.stringify(window.__game.state)));
const coach = () => p.evaluate(() => document.getElementById('coach').classList.contains('on') ? document.querySelector('#coach b').textContent : '');
const waitCoach = async (t) => { for (let i = 0; i < 40; i++) { if ((await coach()) === t) return true; await p.waitForTimeout(150); } return false; };
await p.goto(base + '/?lite=1&dev=1'); await p.waitForSelector('#modal.on #mok', { timeout: 20000 });
console.log('Tutorial');
ck('first run asks you to name your fish', (await p.textContent('#modal h2')) === 'MEET YOUR FIRST FISH');
await p.fill('#mi', 'Pip'); await p.click('#mok');
ck('then prompts to feed', await waitCoach('TIME FOR A SNACK'));
await p.click('nav [data-tab=care]', { force: true }); await p.click('[data-act=feed]'); ck('feed bar appears', await p.evaluate(() => document.getElementById('feedbar').classList.contains('on')));
const s0 = await S(); await p.mouse.click(200, 300); await p.waitForTimeout(400);
const s1 = await S(); ck('feeding pays a shell and lowers hunger', s1.shells === s0.shells + 1 && s1.hunger < s0.hunger, `${s0.shells}→${s1.shells}`);
ck('tutorial moves on to friends', await waitCoach('BETTER TOGETHER')); await p.click('#cbtn');
ck('then offers a free plant', await waitCoach('A GIFT FOR THE TANK'));
await p.click('nav [data-tab=decorate]', { force: true }); await p.waitForSelector('.card'); await p.click('.card[data-k="decor:fern"]');
ck('the plant is free', (await p.textContent('#buy')).includes('FREE'));
await p.click('#buy'); ck('placement bar opens', await p.evaluate(() => document.getElementById('placebar').classList.contains('on')));
await p.mouse.click(120, 600); await p.waitForTimeout(150);
const valid = await p.evaluate(() => !document.getElementById('pok').disabled); ck('a clear spot is valid', valid);
const before = (await S()); await p.click('#pok'); await p.waitForTimeout(300); const after = await S();
ck('placing adds the plant for free', after.decor.length === before.decor.length + 1 && after.shells === before.shells, `${before.decor.length}→${after.decor.length}`);
ck('tutorial ends with a start button', await waitCoach('YOU ARE ALL SET')); await p.click('#cbtn'); await p.waitForTimeout(300);
ck('tutorial saved as finished', (await S()).flags.tut === 5);

console.log('Shopping');
await p.click('nav [data-tab=decorate]', { force: true }); await p.waitForSelector('.card'); await p.click('.card[data-k="decor:red"]');
const sh = (await S()).shells; ck('a plant costs shells', (await p.textContent('#buy')).includes('7'));
await p.click('#buy'); await p.evaluate(() => { const d = window.__tank.decor; for (const [x, z] of [[2.2, 2.8], [-2.6, 2.9], [0.4, 3.0], [3.4, 2.6]]) { d.move(x, z); if (d.preview.valid) break; } document.getElementById('pok').disabled = !window.__tank.decor.preview.valid; }); await p.click('#pok'); await p.waitForTimeout(300);
const s2 = await S(); ck('buying a plant spends shells', s2.shells === sh - 7, `${sh}→${s2.shells}`);
await p.click('nav [data-tab=decorate]', { force: true }); await p.waitForSelector('.card'); await p.click('.card[data-k="decor:torii"]');
ck('locked items explain themselves', (await p.textContent('.detail .note')).includes('level 3') && await p.evaluate(() => document.getElementById('buy').disabled));
await p.evaluate(() => window.__game.dispatch({ t: 'dev', what: 'shells' }, { dev: true })); await p.waitForTimeout(200);
await p.click('[data-cat=FISH]'); await p.click('.card[data-k="fish:goldfish"]'); ck('fish are adoptable', !(await p.evaluate(() => document.getElementById('buy').disabled)));
await p.click('#buy'); await p.waitForSelector('#modal.on #mi'); await p.fill('#mi', 'Mango'); await p.click('#mok'); await p.waitForTimeout(400);
const s3 = await S(); ck('adopting adds a baby fish', s3.fish.length === 2 && s3.fish[1].name === 'Mango' && s3.fish[1].stage === 'baby', JSON.stringify(s3.fish.map((f) => f.name)));
ck('the new fish appears in the tank', (await p.evaluate(() => window.__tank.fishes.length)) === 2);

console.log('Progress');
await p.evaluate(() => window.__game.dispatch({ t: 'dev', what: 'shells' }, { dev: true })); await p.evaluate(() => window.__game.dispatch({ t: 'dev', what: 'shells' }, { dev: true }));
await p.click('nav [data-tab=decorate]', { force: true }); await p.click('[data-cat=FISH]'); await p.click('.card[data-k="fish:neon"]'); await p.click('#buy'); await p.fill('#mi', 'Glow'); await p.click('#mok'); await p.waitForTimeout(400);
const s4 = await S(); ck('a neon school adds four fish', s4.fish.length === 6, `${s4.fish.length} fish`);
ck('the tank levels up', s4.level >= 2, `level ${s4.level}`);
const g0 = (await p.evaluate(() => window.__tank.fishes.map((f) => f.growth)))[0];
await p.evaluate(() => window.__game.dispatch({ t: 'dev', what: 'day' }, { dev: true })); await p.evaluate(() => window.__game.dispatch({ t: 'dev', what: 'day' }, { dev: true })); await p.waitForTimeout(500);
const s5 = await S(); const g1 = (await p.evaluate(() => window.__tank.fishes.map((f) => f.growth)))[0];
ck('fish grow over days', s5.fish[0].stage !== 'baby' && g1 > g0, `${s5.fish[0].stage}, scale ${g0}→${g1}`);
ck('journal records real events', (await p.evaluate(() => window.__game.journal.map((j) => j.text))).some((t) => /grow|adult|level|Mango|brought/i.test(t)), '');
console.log('Care & persistence');
await p.evaluate(() => { const s = window.__game.state; s.glass = 0.7; s.water = 0.4; window.__game.emit('state'); });
await p.click('nav [data-tab=care]', { force: true }); await p.click('[data-act=water]'); await p.waitForTimeout(700); const wS = await S(); ck('water change pays when needed', wS.water > 0.99, 'water ' + wS.water + ' toast ' + await p.textContent('#toast'));
await p.evaluate(() => { window.__game.save(); }); await p.addInitScript(() => localStorage.setItem('ourtank.seen.solo', String(Date.now() - 3 * 3600e3))); await p.reload(); await p.waitForSelector('#tank'); await p.waitForTimeout(1500);
const s6 = await S(); ck('progress survives a reload', s6.fish.length === 6 && s6.decor.length >= 6 && s6.flags.tut === 5, `${s6.fish.length} fish, ${s6.decor.length} decor`);
await p.waitForSelector('#modal.on', { timeout: 15000 });
ck('coming back shows what happened while away', (await p.textContent('#modal h2')) === 'WHILE YOU WERE AWAY' && (await p.$$eval('#modal li', (n) => n.length)) <= 3, (await p.$$eval('#modal li', (n) => n.map((x) => x.textContent))).join(' | '));
await p.click('#mok');
console.log(errors.length ? 'Errors: ' + errors.slice(0, 5).join(' | ') : 'No page errors');
if (errors.length) fails++;
await b.close(); console.log(fails ? `\n${fails} FAILED` : '\nPlaythrough passed'); process.exit(fails ? 1 : 0);
