import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const out = process.env.OUT || '.';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await (await b.newContext({ viewport: { width: 390, height: 760 }, deviceScaleFactor: 1 })).newPage();
p.on('pageerror', (e) => console.log('pageerror:', e.message)); p.on('console', (m) => { if (m.type() === 'error') console.log('console:', m.text()); });
await p.goto('http://localhost:8123/?q=1&dev=1'); await p.waitForSelector('#modal.on #mok', { timeout: 120000 });
await p.click('#mok'); await p.waitForTimeout(800);
const d = (a) => p.evaluate((a) => window.__game.dispatch(a, { dev: true }), a);
await d({ t: 'tut', step: 5 }); for (let i = 0; i < 6; i++) await d({ t: 'dev', what: 'shells' });
const st = await p.evaluate(() => { const s = window.__game.state; s.level = 8; return s.level; }); console.log('level', st);
for (const sp of ['platy', 'danio', 'betta']) console.log(sp, JSON.stringify(await d({ t: 'buyFish', species: sp, name: 'T', seed: 5, rush: true })));
for (const ty of ['bamboo', 'anchor', 'bridge', 'crystal']) console.log(ty, JSON.stringify(await d({ t: 'buyDecor', type: ty, x: ({ bamboo: -3, anchor: 3, bridge: 0, crystal: 2 })[ty], z: ({ bamboo: 1, anchor: 2, bridge: 1.2, crystal: 0.2 })[ty], ry: 0 }).then((r) => r.reason ?? r.ok)));
await d({ t: 'dev', what: 'drift' });
await p.waitForTimeout(4000); await p.screenshot({ path: out + '/s_tank.png' }); console.log('tank');
await p.evaluate(() => window.__ui.open('care')); await p.waitForTimeout(600); await p.screenshot({ path: out + '/s_care.png' });
await p.evaluate(() => window.__ui.showBook()); await p.waitForTimeout(25000); await p.screenshot({ path: out + '/s_book.png' });
await p.click('nav [data-tab=tank]', { force: true }).catch(() => {}); await p.evaluate(() => window.__ui.open('tank')); await p.waitForTimeout(500);
const g = await p.evaluate(() => window.__game.state.drift); console.log('drift', JSON.stringify(g));
await b.close();
