import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const out = process.env.OUT || '.';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const ctx = await b.newContext({ viewport: { width: 390, height: 760 }, deviceScaleFactor: 1 }); const p = await ctx.newPage();
p.on('pageerror', (e) => console.log('pageerror:', e.message));
await p.goto('http://localhost:8123/?q=1&dev=1&tod=afternoon'); await p.waitForSelector('#modal.on #mok', { timeout: 120000 }); await p.click('#mok'); await p.waitForTimeout(800);
const d = (a) => p.evaluate((a) => window.__game.dispatch(a, { dev: true }), a);
await d({ t: 'tut', step: 5 });
await p.screenshot({ path: out + '/v_empty.png' }); console.log('goal:', await p.textContent('#goal'));
await p.evaluate(async () => { const g = window.__game; g.state.level = 8; for (let i = 0; i < 8; i++) await g.dispatch({ t: 'dev', what: 'shells' }, { dev: true }); });
for (const [ty, x, z] of [['anchor', 2.8, 1.5], ['crystal', -2.0, 1.5], ['bamboo', -3.6, 0.3]]) console.log(ty, await d({ t: 'buyDecor', type: ty, x, z, ry: 0 }).then((r) => r.ok));
await d({ t: 'dev', what: 'drift' }); await p.evaluate(() => { window.__cam = [0, 3.2, 19, 0, 2.2, 0]; }); await p.waitForTimeout(6000);
await p.screenshot({ path: out + '/v_decor.png' });
await b.close(); console.log('done');
