import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const out = process.env.OUT || '.';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const ctx = await b.newContext({ viewport: { width: 390, height: 760 }, deviceScaleFactor: 1 }); const p = await ctx.newPage();
p.on('pageerror', (e) => console.log('pageerror:', e.message));
await p.goto('http://localhost:8123/?q=1&dev=1&tod=afternoon'); await p.waitForSelector('#modal.on #mok', { timeout: 120000 }); await p.click('#mok'); await p.waitForTimeout(800);
const d = (a) => p.evaluate((a) => window.__game.dispatch(a, { dev: true }), a);
await d({ t: 'tut', step: 5 });
await p.screenshot({ path: out + '/v_empty.png' }); console.log('goal:', await p.textContent('#goal'));
await p.evaluate(async () => { const g = window.__game; g.state.level = 8; for (let i = 0; i < 8; i++) await g.dispatch({ t: 'dev', what: 'shells' }, { dev: true }); });
for (const [ty, x, z] of [['bamboo', -3.2, 0.3], ['anchor', 3.2, 1.5], ['bridge', 0, 2.7], ['crystal', -1.2, 0.3]]) console.log(ty, await d({ t: 'buyDecor', type: ty, x, z, ry: 0 }).then((r) => r.ok));
await d({ t: 'dev', what: 'drift' }); await p.evaluate(() => { window.__cam = [0, 5, 24, 0, 3.4, 0]; }); await p.waitForTimeout(6000);
await p.screenshot({ path: out + '/v_decor.png' });
const pos = { sx: 290, sy: 495 };
console.log('gift at', JSON.stringify(pos)); await p.mouse.click(pos.sx, pos.sy); await p.waitForTimeout(1500);
console.log('after tap', JSON.stringify(await p.evaluate(() => [window.__game.state.drift, window.__game.state.shells])));
await p.screenshot({ path: out + '/v_after.png' });
await p.evaluate(() => { window.__cam = null; }); await p.waitForTimeout(500);
await p.evaluate(() => window.__ui.open('care')); await p.click('[data-act=photo]'); await p.waitForTimeout(2500); console.log('toast', await p.textContent('#toast'));
await b.close(); console.log('done');
