import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const [,, url, file, js] = process.argv;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 390, height: 760 } });
p.on('pageerror', (e) => console.log('pageerror:', e.message));
await p.goto(url); await p.waitForTimeout(1200);
if (js) await p.evaluate(js);
await p.waitForTimeout(1800);
await p.screenshot({ path: file });
await b.close();
